{% set version = "0.2.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ravetools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ravetools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ravetools/ravetools_{{ version }}.tar.gz
  sha256: 177a3b6fcd6013a270036b495807d01a1dfd3e54dcec101c4a16fac618a311d8

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6 >=2.5.1
    - r-rniftyreg >=2.7.1
    - r-rcpp
    - r-rcppeigen
    - r-digest >=0.6.29
    - r-filearray >=0.1.3
    - r-gsignal >=0.3.5
    - r-pracma
    - r-waveslim >=1.8.2
    - fftw
    - libgomp                       # [linux]
    - llvm-openmp                   # [osx]
  run:
    - r-base
    - r-r6 >=2.5.1
    - r-rniftyreg >=2.7.1
    - r-rcpp
    - r-rcppeigen
    - r-digest >=0.6.29
    - r-filearray >=0.1.3
    - r-gsignal >=0.3.5
    - r-pracma
    - r-waveslim >=1.8.2
    - fftw

test:
  commands:
    - $R -e "library('ravetools')"           # [not win]
    - "\"%R%\" -e \"library('ravetools')\""  # [win]

about:
  home: https://dipterix.org/ravetools/
  license: GPL-2.0-or-later
  summary: |
    Implemented fast and memory-efficient Notch-filter, Welch-periodogram, discrete 
    wavelet spectrogram for minutes of high-resolution signals, fast 3D convolution, 
    image registration, 3D mesh manipulation; providing fundamental toolbox for 
    intracranial Electroencephalography (iEEG) pipelines. 
    Documentation and examples about 'RAVE' project are provided at 
    <https://openwetware.org/wiki/RAVE>, and the paper by John F. Magnotti, 
    Zhengjia Wang, Michael S. Beauchamp (2020) <doi:10.1016/j.neuroimage.2020.117341>; 
    see 'citation("ravetools")' for details.
  license_family: GPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - dipterix
    - beauchamplab
    - conda-forge/r

# Package: ravetools
# Type: Package
# Title: Signal Processing Toolbox for Analyzing 'Electrophysiology' Data
# Version: 0.0.8
# Language: en-US
# Authors@R: c( person("Zhengjia", "Wang", email = "dipterix.wang@gmail.com", role = c("aut", "cre", "cph")), person(family = "Beauchamp lab", email = "beauchamplab@gmail.com", role = c("cph")), person("Karim", "Rahim", email = "karim.rahim@queensu.ca", role = c("cph"), comment = "R package fftwtools"), person(family = "Prerau Lab", role = "cph", comment = "Multitaper Spectrogram Code"), person(family = "RcppParallel Authors", role = "cph", comment = "TinyParallel Code comes from RcppParallel"), person("Marcus", "Geelnard", role = "cph", comment = "TinyThread library") )
# Description: Implemented fast and memory-efficient 'Notch'-filter, 'Welch-periodogram', and discrete wavelet transform algorithm for hours of high-resolution signals; providing fundamental toolbox for 'iEEG' preprocess pipelines. Documentation and examples about 'RAVE' project are provided at <https://openwetware.org/wiki/RAVE>, and the paper by John F. Magnotti, Zhengjia Wang, Michael S. Beauchamp (2020) <doi:10.1016/j.neuroimage.2020.117341>; see 'citation("ravetools")' for details.
# BugReports: https://github.com/dipterix/ravetools/issues
# URL: https://dipterix.org/ravetools/
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.2.1
# Depends: R (>= 4.0.0)
# SystemRequirements: fftw3 (libfftw3-dev (deb), or fftw-devel (rpm))
# Imports: graphics, stats, filearray (>= 0.1.3), Rcpp (>= 1.0.8), waveslim (>= 1.8.2), signal (>= 0.7.7), pracma, digest (>= 0.6.29), splines
# LinkingTo: Rcpp
# Suggests: fftwtools, bit64, microbenchmark, testthat
# NeedsCompilation: yes
# Packaged: 2022-10-14 03:57:02 UTC; dipterix
# Author: Zhengjia Wang [aut, cre, cph], Beauchamp lab [cph], Karim Rahim [cph] (R package fftwtools), Prerau Lab [cph] (Multitaper Spectrogram Code), RcppParallel Authors [cph] (TinyParallel Code comes from RcppParallel), Marcus Geelnard [cph] (TinyThread library)
# Maintainer: Zhengjia Wang <dipterix.wang@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-10-14 12:00:10 UTC
